### ISSUE TITLE
Collect console.debug, info and warn too

### ISSUE THREAD

**Issue by fromi** [DataDog/browser-sdk#400]
Right now only console.error is being enhanced to report errors to Datadog.
I would like too:
- Be able to redirect console.debug, console.info and console.warn to Datadog (depending on the log level of course).
- Be able to hide console messages in my production environment.

**Reasons:**
Right now I log to datadog when I am in my production environment. In my localhost environment, I want to log into the console.
If I use "datadogLogs.logger.debug", in my localhost environnement I have on those ugly warnings: `logs.logger.debug' not yet available, please call '.init()' first.`
I could wrap all my log conditionally like this of course:
```
      if (process.env.REACT_APP_DATADOG_CLIENT_TOKEN) {
        datadogLogs.logger.debug('...')
      } else {
        console.debug('...')
      }
```
But that's way too much code for one log.

**Suggestion**
Improve [startConsoleTracking](https://github.com/DataDog/browser-sdk/blob/0247a70d5cbef09e38b62cc7cda846b7c9c10440/packages/core/src/errorCollection.ts#L86) to handle all logging methods from the console.
Also, do not apply [originalConsoleError](https://github.com/DataDog/browser-sdk/blob/0247a70d5cbef09e38b62cc7cda846b7c9c10440/packages/core/src/errorCollection.ts#L89) all the time: use a configurable parameter to skip this part conditionnaly.

**Comment by bcaudan** [comment]
Hello @fromi,

Thanks for the feedback!
It is something that we plan to do in the coming weeks.

We will ping here when it will be available.

**Comment by barshopen** [comment]
Hi guys, any update? 
Also are you planning to also add console.log to this collection process?

**Comment by bcaudan** [comment]
Hi @barshopen, it is not in our current priority but it is still something that we want to do at some point.
Yes, `console.log` should also be addressed with other console APIs.

**Comment by schauhandiv** [comment]
According to https://www.datadoghq.com/blog/monitor-javascript-console-logs/ & https://docs.datadoghq.com/logs/log_collection/javascript/ console.log should go to Datadog. In my react app, I am using the @datadog/browser-logs npm pkg, but I can't see any logs in Datadog. I also tried the datadogLogs.logger.info(), that doesn't send any logs to Datadog either. I haven't been able to send send logs from my React app to Datadog. The user interactions and console errors do go, but no logs. Is that feature working as per the two articles above?

**Comment by gwdp** [comment]
Logrocket does automatic `console` forward to their service. Evaluating migrating to DG and this feature a deal-breaker for us. (200k+ sessions monthly).

Not a surprise Logrocket is the leader in this segment right now. while DG is slowly trying to catch up. 2 years on the most basic RUM feature you could ask for and still not a priority.

**Comment by BenoitZugmeyer** [comment]
@gwdp Thanks for your feedback. We are actively working on it and fine tune the last details before releasing it. Stay tuned!

**Comment by gwdp** [comment]
Hi @BenoitZugmeyer, really appreciate your quick reply.
I seem `forwardConsoleLogs` popping up :) Hopefully, we will be able to use it soon.

In the meanwhile, if anyone needs it, I was able to make it work with very few lines of code. Still, not the ideal solution, but gets the job done.

```
  datadogLogs.init({ ...config.DatadogOptions }); //->> @datadog/browser-logs
  (() => {
    const { log, error, debug, warn } = console;
    global.console.info = (...args) => { datadogLogs.logger.info(...args); log(...args); };
    global.console.log = (...args) => { datadogLogs.logger.info(...args); log(...args); };
    global.console.error = (...args) => { datadogLogs.logger.error(...args); error(...args); };
    global.console.debug = (...args) => { datadogLogs.logger.debug(...args); debug(...args); };
    global.console.warn = (...args) => { datadogLogs.logger.warn(...args); warn(...args); };
  })();  
```

**Comment by BenoitZugmeyer** [comment]
This feature has been released in the Logs Browser SDK v4.8.0! See `forwardConsoleLogs` initialization parameter in the [documentation](https://docs.datadoghq.com/logs/log_collection/javascript/#initialization-parameters)
